In [16]:
import pandas as pd

import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff
from plotly.subplots import make_subplots
import matplotlib.pyplot as plt

In [17]:
#load datasets
path_1 = 'data/depp-rers-2017-donnees-fiche-02-06-810812.xls'
path_2 = 'data/fr-en-baccalaureat-par-academie.csv'
path_3 = 'data/fr-en-college-effectifs-niveau-sexe-lv.csv'
path_4 = 'data/fr-en-dnb-par-etablissement.csv'
path_5 = 'data/fr-en-reussite-au-baccalaureat-origine-sociale.csv'

taille_collège_lycée_data = pd.read_excel(path_1)
bac_academie_data = pd.read_csv(path_2, delimiter=';')
college_effectif_data = pd.read_csv(path_3, delimiter=';')
brevet_établissement_data = pd.read_csv(path_4, delimiter=';')
bac_origine_data = pd.read_csv(path_5, delimiter=';')

# Exploration bac / lycée data

## 1 - Bac origine Data

In [18]:
# Basic stats
print(f'Number of rows : {bac_origine_data.shape[0]}\n')

print('Display of dataset: ')
display(bac_origine_data.head())

print('Basics statistics :')
data_desc = bac_origine_data.describe(include='all')
display(data_desc)

print('Percentage of missing values: ')
display(100 * bac_origine_data.isnull().sum() / bac_origine_data.shape[0])

missing_values = bac_origine_data.isnull().any().any()
if missing_values :
    print('There are missing values in the dataset')
else :
    print('There are no missing values in the dataset')

Number of rows : 348

Display of dataset:

,Année,Origine sociale,Nombre d'admis au baccalaureat général,Pourcentage d'admis au baccalaureat général,Nombre d'admis au baccalauréat technologique,Pourcentage d'admis au baccalauréat technologique,Nombre d'admis au baccalauréat professionnel,Pourcentage d'admis au baccalauréat professionnel,Nombre d'admis au baccalauréat,Pourcentage d'admis au baccalauréat
0,1997,Autres personnes sans activité professionnelle,8844,66.4,8679,71.2,5883,73.7,23406,69.9
1,1997,Employés,36083,73.9,23852,78.4,12681,81.3,72616,76.5
2,1998,Employés,37362,76.9,26097,80.3,13763,78.1,77222,78.2
3,1998,Ensemble,275113,79.2,144830,79.5,81573,76.7,501516,78.9
4,1998,Indéterminé,4338,64.3,4322,72.4,6488,70.8,15148,69.2

Basics statistics :

,Année,Origine sociale,Nombre d'admis au baccalaureat général,Pourcentage d'admis au baccalaureat général,Nombre d'admis au baccalauréat technologique,Pourcentage d'admis au baccalauréat technologique,Nombre d'admis au baccalauréat professionnel,Pourcentage d'admis au baccalauréat professionnel,Nombre d'admis au baccalauréat,Pourcentage d'admis au baccalauréat
count,348.000000,348,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000
unique,NaN,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Autres personnes sans activité professionnelle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2011.000000,NaN,53213.580460,87.448851,23117.169540,84.602586,23086.853448,81.988506,99417.603448,85.651149
std,8.378647,NaN,82892.404211,8.084476,35759.187672,7.472306,38480.606435,5.825724,153301.782123,7.315427
min,1997.000000,NaN,2923.000000,61.900000,848.000000,66.500000,350.000000,65.400000,4958.000000,67.400000
25%,2004.000000,NaN,7474.000000,82.375000,2695.000000,79.175000,3664.500000,78.675000,16542.250000,80.750000
50%,2011.000000,NaN,24724.000000,88.800000,12583.000000,85.050000,10771.500000,81.750000,56111.500000,86.000000
75%,2018.000000,NaN,49502.500000,94.025000,23709.500000,90.900000,23211.000000,86.125000,93914.500000,91.525000
max,2025.000000,NaN,384158.000000,99.100000,152778.000000,97.600000,190899.000000,94.900000,722971.000000,98.600000

Percentage of missing values:

Année                                                0.0
Origine sociale                                      0.0
Nombre d'admis au baccalaureat général               0.0
Pourcentage d'admis au baccalaureat général          0.0
Nombre d'admis au baccalauréat technologique         0.0
Pourcentage d'admis au baccalauréat technologique    0.0
Nombre d'admis au baccalauréat professionnel         0.0
Pourcentage d'admis au baccalauréat professionnel    0.0
Nombre d'admis au baccalauréat                       0.0
Pourcentage d'admis au baccalauréat                  0.0
dtype: float64

There are no missing values in the dataset

In [19]:
column_feature = [
    "Nombre d'admis au baccalaureat général",
    "Nombre d'admis au baccalauréat technologique",
    "Nombre d'admis au baccalauréat professionnel",
    "Nombre d'admis au baccalauréat",
    "Origine sociale"
]

fig = make_subplots(rows=3, cols=2)
row = 1
col = 1
for column in column_feature:           
    fig.add_trace(go.Histogram(x=bac_origine_data[column], name=column),row=row, col=col)
    col += 1 
    if col >2:
        row += 1 
        col =1
fig.update_layout(title= dict(text='Distribution', x=0.5))
fig.update_layout(autosize=False, width=1200, height=1000)

fig.show()

## 2 - Bac académie Data

In [20]:
# Basic stats
print(f'Number of rows : {bac_academie_data.shape[0]}\n')

print('Display of dataset: ')
display(bac_academie_data.head())

print('Basics statistics :')
data_desc = bac_academie_data.describe(include='all')
display(data_desc)

print('Percentage of missing values: ')
display(100 * bac_academie_data.isnull().sum() / bac_academie_data.shape[0])

missing_values = bac_academie_data.isnull().any().any()
if missing_values :
    print('There are missing values in the dataset')
else :
    print('There are no missing values in the dataset')

Number of rows : 43217

Display of dataset:

,Session,Code académie,Libellé académie,Sexe,Statut du candidat,Voie,Série,Diplôme spécialité,Nombre d'inscrits,Nombre de présents,...,"Nombre d'ajournés, passant les épreuves du 2nd groupe",Nombre d'admis à l'issue du 2nd groupe,Nombre de refusés à l'issue du 2nd groupe,Nombre d'admis totaux,Nombre d'admis avec mention TB avec les félicitations du jury,Nombre d'admis avec mention TB sans les félicitations du jury,Nombre d'admis avec mention B,Nombre d'admis avec mention AB,Nombre d'admis sans mention,Nombre de refusés totaux
0,2021,4,BORDEAUX,FEMININ,SCOLAIRE,BAC PROFESSIONNEL,BAC PRO SERV,BAC PRO 33004 ACC.SOINS-S.PERS. OPT.EN STRUCTUR,471,470,...,8,4,4,453,0,29,164,170,90,17
1,2021,4,BORDEAUX,FEMININ,SCOLAIRE,BAC PROFESSIONNEL,BAC PRO SERV,BAC PRO 34304 HYGIENE PROPRETE STERILISATION,10,10,...,0,0,0,7,0,0,0,5,2,3
2,2021,4,BORDEAUX,FEMININ,SCOLAIRE,BAC PROFESSIONNEL,BAC PRO SERV,BAC PRO AG 33002 SERV PERS TERRIT,419,409,...,0,0,0,394,0,22,76,142,154,15
3,2021,4,BORDEAUX,FEMININ,SCOLAIRE,BAC TECHNOLOGIQUE,BAC STD2A,BAC STD2A SCIENCES & TECHNO. DESIGN-ARTS APPLI...,178,178,...,4,2,2,176,2,10,70,69,25,2
4,2021,4,BORDEAUX,FEMININ,SCOLAIRE,BAC TECHNOLOGIQUE,BAC STL,BAC STL BIOCHIM.-BIOLOGIE-BIOTECHNOL.,143,143,...,5,4,1,142,0,9,27,49,57,1

Basics statistics :

,Session,Code académie,Libellé académie,Sexe,Statut du candidat,Voie,Série,Diplôme spécialité,Nombre d'inscrits,Nombre de présents,...,"Nombre d'ajournés, passant les épreuves du 2nd groupe",Nombre d'admis à l'issue du 2nd groupe,Nombre de refusés à l'issue du 2nd groupe,Nombre d'admis totaux,Nombre d'admis avec mention TB avec les félicitations du jury,Nombre d'admis avec mention TB sans les félicitations du jury,Nombre d'admis avec mention B,Nombre d'admis avec mention AB,Nombre d'admis sans mention,Nombre de refusés totaux
count,43217.000000,43217.000000,43217,43217,43217,43217,43217,43217,43217.000000,43217.000000,...,43217.000000,43217.000000,43217.000000,43217.000000,43217.000000,43217.000000,43217.000000,43217.000000,43217.000000,43217.000000
unique,NaN,NaN,30,4,5,3,23,310,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NANTES,MASCULIN,SCOLAIRE,BAC PROFESSIONNEL,BAC PRO PROD,BAC GENE 10019 BAC GENERAL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,1972,19307,23133,34830,18359,715,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2023.026494,17.566027,NaN,NaN,NaN,NaN,NaN,NaN,86.353079,85.840803,...,6.269061,4.376981,1.892080,78.667075,0.831478,6.765324,16.891964,26.374343,27.803966,7.173728
std,1.413073,14.360495,NaN,NaN,NaN,NaN,NaN,NaN,647.273492,647.234306,...,44.633740,31.967000,12.986692,624.645612,11.837864,80.729542,161.849247,202.235609,179.021704,28.379103
min,2021.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2022.000000,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,2.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2023.000000,15.000000,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,7.000000,...,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,1.000000,2.000000,2.000000,1.000000
75%,2024.000000,23.000000,NaN,NaN,NaN,NaN,NaN,NaN,29.000000,28.000000,...,1.000000,1.000000,0.000000,24.000000,0.000000,1.000000,5.000000,8.000000,10.000000,4.000000
max,2025.000000,70.000000,NaN,NaN,NaN,NaN,NaN,NaN,22509.000000,22509.000000,...,1985.000000,1502.000000,503.000000,21711.000000,483.000000,3215.000000,6521.000000,7175.000000,6408.000000,1065.000000

Percentage of missing values:

Session                                                          0.0
Code académie                                                    0.0
Libellé académie                                                 0.0
Sexe                                                             0.0
Statut du candidat                                               0.0
Voie                                                             0.0
Série                                                            0.0
Diplôme spécialité                                               0.0
Nombre d'inscrits                                                0.0
Nombre de présents                                               0.0
Nombre d'admis au 1er groupe                                     0.0
Nombre de refusés au 1er groupe                                  0.0
Nombre d'ajournés, passant les épreuves du 2nd groupe            0.0
Nombre d'admis à l'issue du 2nd groupe                           0.0
Nombre de refusés à l'issue du 2nd groupe                        0.0
Nombre d'admis totaux                                            0.0
Nombre d'admis avec mention TB avec les félicitations du jury    0.0
Nombre d'admis avec mention TB sans les félicitations du jury    0.0
Nombre d'admis avec mention B                                    0.0
Nombre d'admis avec mention AB                                   0.0
Nombre d'admis sans mention                                      0.0
Nombre de refusés totaux                                         0.0
dtype: float64

There are no missing values in the dataset